# Generated by Django 2.0 on 2021-01-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=255)),
                ('linkman', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('number_of_employee', models.CharField(max_length=255)),
                ('company_address', models.CharField(max_length=255)),
                ('real_boss_and_phone', models.CharField(max_length=255)),
                ('boss_birthday', models.DateField(blank=True, default='1111-11-11', null=True)),
                ('boss_chinese_zodiac', models.CharField(max_length=255)),
                ('company_birthday', models.DateField(blank=True, null=True)),
                ('area', models.CharField(max_length=255)),
                ('saleman', models.CharField(max_length=255)),
                ('sale_product_all_is_qb', models.CharField(max_length=255)),
                ('other_product_name', models.CharField(max_length=255)),
                ('total_annual_sales', models.CharField(max_length=255)),
                ('Products_accounted_for_qb', models.CharField(max_length=255)),
                ('Products_accounted_for_chenpi', models.CharField(max_length=255)),
                ('Products_accounted_for_ganpucha', models.CharField(max_length=255)),
                ('area_responsible', models.CharField(max_length=255)),
                ('customer_level', models.CharField(max_length=255)),
                ('task_money', models.CharField(max_length=255)),
                ('finish_money', models.CharField(max_length=255)),
                ('purchase_amount_of_qiyueguo', models.CharField(max_length=255)),
                ('the_storage_amount_of_xinpi', models.CharField(max_length=255)),
                ('the_qbproduct_sales_first', models.CharField(max_length=255)),
                ('the_qbproduct_sales_second', models.CharField(max_length=255)),
                ('the_qbproduct_sales_third', models.CharField(max_length=255)),
                ('fenxiao_number_name', models.CharField(max_length=255)),
                ('zhuangui_number_name', models.CharField(max_length=255)),
                ('customer_specific_circumstance', models.CharField(max_length=255)),
                ('question', models.CharField(max_length=255)),
                ('remark', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Manage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Saleman',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('superior', models.CharField(max_length=255)),
                ('territory', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('superiorname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
