# Generated by Django 2.0 on 2021-01-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20210128_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalemanReceivable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexdate', models.DateField(blank=True, null=True)),
                ('saleman', models.CharField(max_length=255, null=True)),
                ('area', models.CharField(max_length=255, null=True)),
                ('money', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
