# Generated by Django 2.0 on 2021-01-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_salemanreceivable'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalemanSaleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(blank=True, null=True)),
                ('customer', models.CharField(max_length=255, null=True)),
                ('product', models.CharField(max_length=255, null=True)),
                ('saleman', models.CharField(max_length=255, null=True)),
                ('sale_money', models.CharField(max_length=255, null=True)),
                ('area', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
