# Generated by Django 2.0 on 2021-01-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_salemansaleinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='salemansaleinfo',
            name='index_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
